const mockedProducts = [
  {
    id: "1",
    brand: "Porsche",
    model: "Porsche 718",
    color: "Azul",
    year: 2002,
    fuel: "Gasolina",
    mileage: 2500,
    price: 10500.0,
    fipePrice: 11000.0,
    coverImage: "string",
    description: "Porsche em excelente estado",
    sellerId: "123",
  },
  {
    id: "2",
    brand: "Fiat",
    model: "Idea",
    color: "Prata",
    year: 2002,
    fuel: "Flex",
    mileage: 22500,
    price: 5500.0,
    fipePrice: 6000.0,
    coverImage: "string",
    description: "Idea em excelente estado",
    sellerId: "123",
  },
  {
    id: "3",
    brand: "Honda",
    model: "Fit",
    color: "Vermelho",
    year: 2012,
    fuel: "Alcool",
    mileage: 32500,
    price: 9500.0,
    fipePrice: 9000.0,
    coverImage: "string",
    description: "Fit em excelente estado",
    sellerId: "123",
  },
  {
    id: "4",
    brand: "Toyota",
    model: "Corolla",
    color: "Preto",
    year: 2022,
    fuel: "Híbrido",
    mileage: 15000,
    price: 62500.0,
    fipePrice: 65000.0,
    coverImage: "string",
    description: "Corolla em excelente estado",
    sellerId: "123",
  },
  {
    id: "5",
    brand: "VolksWagen",
    model: "Touareg 718",
    color: "Azul",
    year: 2020,
    fuel: "Gasolina",
    mileage: 2500,
    price: 90500.0,
    fipePrice: 95000.0,
    coverImage: "string",
    description: "Touareg em excelente estado",
    sellerId: "123",
  },
  {
    id: "6",
    brand: "Ford",
    model: "Ka",
    color: "Branco",
    year: 2015,
    fuel: "Flex",
    mileage: 35500,
    price: 20500.0,
    fipePrice: 21000.0,
    coverImage: "string",
    description: "Ka em excelente estado",
    sellerId: "123",
  },
];

export default mockedProducts;
